### ISSUE TITLE
Figure out why Height is negative sometimes for the alignment block

### ISSUE THREAD

**Issue by szczura** [RickLeinecker/SeeShells#293]
Is maxStackedNodes not getting the correct max?

Exception that sometimes happens on parsing:
2020-03-30 18:55:10.0979|FATAL|SeeShells.App|An unhandled exception occurred: '-210' is not a valid value for property 'Height'. -    at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.FrameworkElement.set_Height(Double value)
   at SeeShells.UI.Pages.TimelinePage.AddTimeline(List`1 nodesCluster) in C:\Users\Klayton\OneDrive\Senior Design 2\SeeShells\WPF\SeeShells\SeeShells\UI\Pages\TimelinePage.xaml.cs:line 295
   at SeeShells.UI.Pages.TimelinePage.BuildTimeline() in C:\Users\Klayton\OneDrive\Senior Design 2\SeeShells\WPF\SeeShells\SeeShells\UI\Pages\TimelinePage.xaml.cs:line 257
   at SeeShells.UI.Pages.TimelinePage..ctor() in C:\Users\Klayton\OneDrive\Senior Design 2\SeeShells\WPF\SeeShells\SeeShells\UI\Pages\TimelinePage.xaml.cs:line 41
   at SeeShells.UI.Pages.Home.<ParseButton_Click>d__17.MoveNext() in C:\Users\Klayton\OneDrive\Senior Design 2\SeeShells\WPF\SeeShells\SeeShells\UI\Pages\Home.xaml.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by klaki892** [comment]
Steps to Reproduce:
1. Grab the Corporate Fraud VM from the link distributed to the team 
2. Run the VM
3. Plug in a flashdrive containing seeShells.exe or a (or a shortcut to it) in the top level folder
4. Run a live registry parse on SeeShells
5. Observe crashing behavior

Issue is present in commit  26a14e9334ea38f4d0741518e4f33050ae5cba7a
